### ISSUE TITLE
Issue with django.contrib.messages

### ISSUE THREAD

**Issue by dulguun-tuguldur** [LorenzoProd/django-persistent-filters#1]
Hello, using this persistent filter blocks `django.contrib.messages`. I am looking for solutions. 

I will update the issue if I find any solution.

**Comment by LorenzoProd** [comment]
Hi, I've just tested the library and it seems to be working properly with django.contrib.messages.
Could you please provide specific examples that demonstrate the issue?

**Comment by dulguun-tuguldur** [comment]
> Hi, I've just tested the library and it seems to be working properly with django.contrib.messages. Could you please provide specific examples that demonstrate the issue?

Sorry for late response, I made new project which demonstrates the issue.

https://github.com/dulguun-tuguldur/django-persistent-filter-example

Run the project and when you go to `/test/`. There will be initial message and link named `Some function`.

My project's main workflow was using `Some function` to modify the record and showing response toast with `messages`.

So when you click `Some function` it should show new toast `New error from messages`.

But when I configure the `django-persistent-filter` in settings.py. It is not showing new toast from `SomeFunctionView` anymore.

---

Although I can workaround this by redirecting to filtered URL immediately by making changes in PR below.

https://github.com/dulguun-tuguldur/django-persistent-filter-example/pull/1/files

**Comment by LorenzoProd** [comment]
Dear, i followed all the steps, uncommented the "/test/" url in PERSISTENT_FILTERS_URLS;
So i've clicked on "Some function" button and "new error from messages" appears. Seems it's works.

![Senza nome](https://github.com/LorenzoProd/django-persistent-filters/assets/43520915/acc1216f-ecbe-4253-9ad2-5c39e37aa8f7)

**Comment by dulguun-tuguldur** [comment]
My fault, I forgot to include the query params. I pushed my changes.

I'm guessing the issue is `messages` is pushing message to the `root` URL while `django-persistent-filter` redirects it to URL with query params.


https://github.com/LorenzoProd/django-persistent-filters/assets/127603807/0683f57a-057f-4b68-aa8e-06743f4b6dab

**Comment by LorenzoProd** [comment]
Dear,
in the file `settings.py`, put the middleware `persistent_filters.middleware.PersistentFiltersMiddleware` just above `django.contrib.messages.middleware.MessageMiddleware`.

```py
MIDDLEWARE = [
    [...]
    'persistent_filters.middleware.PersistentFiltersMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    [...] 
]
```

**Comment by dulguun-tuguldur** [comment]
> Dear, in the file `settings.py`, put the middleware `persistent_filters.middleware.PersistentFiltersMiddleware` just above `django.contrib.messages.middleware.MessageMiddleware`.
> 
> ```python
> MIDDLEWARE = [
>     [...]
>     'persistent_filters.middleware.PersistentFiltersMiddleware',
>     'django.contrib.messages.middleware.MessageMiddleware',
>     [...] 
> ]
> ```

Thank you so much, this fixed the issue.
